const categories={wash:{title:'Lavadoras',goal:'Objetivo: 9–10 kg · A · autodosificación'},dry:{title:'Secadoras',goal:'Objetivo: 8 kg · bomba de calor · sin sobrepagar'},micro:{title:'Microondas',goal:'Objetivo: integrable · cristal blanco · combinar con horno'}};
let data={products:[]};
const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(n);
function priceText(p){if(p.priceLabel)return p.priceLabel;if(p.priceMin&&p.priceMax)return `≈ ${euro(p.priceMin)}–${euro(p.priceMax)}`;return p.price?euro(p.price):'Vigilar precio'}
function card(p){return `<article class="panel product">${p.favorite?'<span class="star">★</span>':''}<div class="brand">${p.brand}</div><div class="model">${p.model}</div><div class="deal">${priceText(p)} ${p.oldPrice?`<span class="old">${euro(p.oldPrice)}</span>`:''}</div><div class="chips">${p.chips.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="score">Encaje ${String(p.score).replace('.',',')}/10</div><div class="bar"><span style="width:${p.score*10}%"></span></div><div class="muted">${p.note}</div>${p.url?`<div class="actions"><a class="btn primary" href="${p.url}" target="_blank" rel="noopener">Ver oferta / fabricante</a></div>`:''}</article>`}
function render(filter='all'){const root=document.getElementById('catalog');root.innerHTML='';Object.entries(categories).forEach(([key,c])=>{if(filter!=='all'&&filter!==key)return;const ps=data.products.filter(p=>p.category===key);if(!ps.length)return;root.insertAdjacentHTML('beforeend',`<section class="section"><div class="section-head"><h2>${c.title}</h2><span class="muted">${c.goal}</span></div><div class="products">${ps.map(card).join('')}</div></section>`)});}
async function load(){try{const r=await fetch('data/electrodomesticos.json',{cache:'no-store'});data=await r.json();render();document.getElementById('updated').textContent=data.updated;const fav=data.products.filter(p=>p.favorite);const total=fav.reduce((s,p)=>s+(p.price??p.priceMin??0),0);document.getElementById('locatedBudget').textContent=`≈ ${euro(total)}`;}catch(e){document.getElementById('catalog').innerHTML='<div class="empty">No se pudo cargar el catálogo. En GitHub Pages funcionará normalmente; si abres index.html directamente desde el disco, el navegador puede bloquear la carga del JSON.</div>';}}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)}));
const prefix='casa_electro_v3_';const fields=[...document.querySelectorAll('[data-store]')];fields.forEach(el=>{el.value=localStorage.getItem(prefix+el.dataset.store)||'';el.addEventListener('input',()=>{localStorage.setItem(prefix+el.dataset.store,el.value);const s=document.getElementById('saveStatus');s.textContent='✓ Guardado en este navegador';s.classList.add('saved');clearTimeout(window._t);window._t=setTimeout(()=>{s.textContent='Los cambios se guardan al escribir.';s.classList.remove('saved')},1400)})});
document.getElementById('clearBtn').addEventListener('click',()=>{if(!confirm('¿Borrar todas las medidas y notas guardadas en este navegador?'))return;fields.forEach(el=>{localStorage.removeItem(prefix+el.dataset.store);el.value=''})});
document.getElementById('exportBtn').addEventListener('click',()=>{const obj={version:3,exported:new Date().toISOString(),measurements:Object.fromEntries(fields.map(el=>[el.dataset.store,el.value]))};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download='casa-electrodomesticos-datos.json';a.click();URL.revokeObjectURL(a.href)});
document.getElementById('importFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());const m=obj.measurements||{};fields.forEach(el=>{if(Object.hasOwn(m,el.dataset.store)){el.value=m[el.dataset.store];localStorage.setItem(prefix+el.dataset.store,el.value)}});document.getElementById('saveStatus').textContent='✓ Datos importados';}catch{alert('El fichero no parece ser una exportación válida.')}e.target.value='';});
load();
